export const ADVERTISING_MODULE = 'ADVERTISING_MODULE';

export const MAX_CAMPAIGN_NAME_LENGTH = 100;
export const MIN_CAMPAIGN_NAME_LENGTH = 3;
export const MAX_TARGET_JSON_SIZE = 10240;

export const SPONSORED_RESULTS_LIMIT = 5;
export const SPONSORED_WEIGHT_DEFAULT = 1;
export const SPONSORED_WEIGHT_MAX = 10;
